import "./globals.css";
import { Roboto } from "next/font/google";

export const metadata = {
  title: "Controle de remédio",
  description: "Generated by create next app",
};
const roboto = Roboto({ subsets: ["latin"], weight:[ '100' , '300' , '400' , '500' , '700' , '900' ] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-gradient-to-bl from-blue-400 to-blue-500 h-screen w-screen`}
      >
        {children}
      </body>
    </html>
  );
}
